name: fuel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  google_sign_in: ^6.2.0
  provider: ^6.1.2
  animated_bottom_navigation_bar: ^1.0.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0
  http: ^0.13.6
  intl: 0.20.2 
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  image_picker: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  dropdown_search: ^5.0.6
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.4
  connectivity_plus: ^5.0.2
  firebase_messaging: ^15.2.9
  awesome_notifications: ^0.10.1
  share_plus: ^11.0.0
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  uri: ^1.0.0
  payhere_mobilesdk_flutter: ^3.2.0

  
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo.jpeg
    - assets/images/bike.png
    - assets/google_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpeg"
